# Generated by Django 4.2.7 on 2024-11-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="dxf",
            field=models.FileField(
                upload_to="infra/table/dxf/", verbose_name="dxfファイル"
            ),
        ),
    ]
