# Generated by Django 4.2.7 on 2024-11-05 04:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0002_alter_table_dxf"),
    ]

    operations = [
        migrations.CreateModel(
            name="NameEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "alphabet",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(regex="[A-Za-z]+")
                        ],
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="infra.article",
                    ),
                ),
            ],
        ),
    ]
