# Generated by Django 4.2.7 on 2024-11-05 06:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0005_nameentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "材料",
                    models.CharField(
                        choices=[
                            ("鋼", "鋼"),
                            ("コンクリート", "コンクリート"),
                            ("ゴム", "ゴム"),
                            ("アスファルト", "アスファルト"),
                            ("塩ビ", "塩ビ"),
                            ("その他", "その他"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PartsName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("部材名", models.CharField(max_length=255)),
                ("記号", models.CharField(max_length=50)),
                ("主要部材", models.BooleanField()),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("material", models.ManyToManyField(to="infra.material")),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.AlterField(
            model_name="table",
            name="article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="infra.article",
                verbose_name="案件名",
            ),
        ),
        migrations.CreateModel(
            name="PartsNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="(^\\d{4}$)|(^\\d{4}~\\d{4}$)"
                            )
                        ],
                    ),
                ),
                ("symbol", models.CharField(max_length=100)),
                ("main_frame", models.BooleanField()),
                ("span_number", models.CharField(max_length=50)),
                (
                    "unique_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="infra.article",
                    ),
                ),
                (
                    "infra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="infra.infra",
                        verbose_name="Infra",
                    ),
                ),
                ("material", models.ManyToManyField(to="infra.material")),
                (
                    "parts_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="infra.partsname",
                        verbose_name="部材名",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="partsnumber",
            constraint=models.UniqueConstraint(
                fields=("parts_name", "number", "span_number", "infra"),
                name="unique_parts_number",
            ),
        ),
    ]
