# Generated by Django 4.2.7 on 2024-11-05 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0006_material_partsname_alter_table_article_partsnumber_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FullReportData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parts_name", models.CharField(max_length=255)),
                ("damage_name", models.CharField(max_length=255)),
                ("parts_split", models.CharField(max_length=255)),
                ("four_numbers", models.CharField(max_length=255)),
                ("join", models.CharField(max_length=255)),
                (
                    "picture_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "this_time_picture",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "last_time_picture",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("textarea_content", models.CharField(max_length=255)),
                ("damage_coordinate_x", models.CharField(max_length=255)),
                ("damage_coordinate_y", models.CharField(max_length=255)),
                (
                    "picture_coordinate_x",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "picture_coordinate_y",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("span_number", models.CharField(max_length=255)),
                ("special_links", models.CharField(max_length=255)),
                (
                    "measurement",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "damage_size",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "classification",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("pattern", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="infra.article"
                    ),
                ),
                (
                    "infra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="infra.infra",
                        verbose_name="Infra",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="infra.table"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DamageList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parts_name", models.CharField(max_length=255)),
                ("symbol", models.CharField(max_length=255)),
                ("number", models.CharField(max_length=255)),
                ("material", models.CharField(max_length=255)),
                ("main_parts", models.CharField(max_length=255)),
                ("damage_name", models.CharField(max_length=255)),
                (
                    "damage_lank",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "classification",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("pattern", models.CharField(blank=True, max_length=255, null=True)),
                ("span_number", models.CharField(max_length=255)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="infra.article",
                    ),
                ),
                (
                    "infra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="infra.infra",
                        verbose_name="Infra",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BridgePicture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="photos/")),
                ("picture_number", models.IntegerField(blank=True, null=True)),
                ("damage_name", models.CharField(max_length=255)),
                ("parts_split", models.CharField(max_length=255)),
                ("damage_coordinate_x", models.CharField(max_length=255)),
                ("damage_coordinate_y", models.CharField(max_length=255)),
                ("memo", models.TextField()),
                (
                    "picture_coordinate_x",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "picture_coordinate_y",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("span_number", models.CharField(max_length=255)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="infra.article"
                    ),
                ),
                (
                    "infra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="infra.infra",
                        verbose_name="橋梁名",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="infra.table"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="fullreportdata",
            constraint=models.UniqueConstraint(
                fields=(
                    "parts_name",
                    "damage_name",
                    "parts_split",
                    "join",
                    "this_time_picture",
                    "infra",
                    "article",
                    "damage_coordinate_x",
                    "damage_coordinate_y",
                    "span_number",
                    "special_links",
                ),
                name="unique_parts_damage",
            ),
        ),
        migrations.AddConstraint(
            model_name="damagelist",
            constraint=models.UniqueConstraint(
                fields=(
                    "parts_name",
                    "symbol",
                    "number",
                    "material",
                    "main_parts",
                    "damage_name",
                    "span_number",
                    "infra",
                ),
                name="unique_damage_list",
            ),
        ),
        migrations.AddConstraint(
            model_name="bridgepicture",
            constraint=models.UniqueConstraint(
                fields=(
                    "image",
                    "damage_coordinate_x",
                    "damage_coordinate_y",
                    "span_number",
                    "table",
                    "infra",
                    "article",
                ),
                name="unique_bridge_picture",
            ),
        ),
    ]
