# Generated by Django 4.2.7 on 2024-11-07 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0007_fullreportdata_damagelist_bridgepicture_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DamageComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parts_name", models.CharField(max_length=255)),
                ("comment_parts_name", models.CharField(max_length=255)),
                ("replace_name", models.CharField(max_length=255)),
                (
                    "parts_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("main_parts", models.CharField(max_length=255)),
                ("material", models.CharField(max_length=255)),
                ("damage_name", models.CharField(max_length=255)),
                ("number", models.IntegerField(blank=True, null=True)),
                (
                    "damage_max_lank",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "damage_min_lank",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "this_time_picture",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("jadgement", models.CharField(blank=True, max_length=255, null=True)),
                ("cause", models.CharField(blank=True, max_length=255, null=True)),
                ("comment", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "auto_comment",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("span_number", models.CharField(max_length=255)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="infra.article",
                    ),
                ),
                (
                    "infra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="infra.infra",
                        verbose_name="Infra",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="damagecomment",
            constraint=models.UniqueConstraint(
                fields=(
                    "parts_name",
                    "main_parts",
                    "damage_name",
                    "span_number",
                    "infra",
                ),
                name="unique_damage_comment",
            ),
        ),
    ]
