# Generated by Django 5.1.3 on 2024-12-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0008_damagecomment_damagecomment_unique_damage_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="fullreportdata",
            name="excel_damage_lank",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="fullreportdata",
            name="excel_damage_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="fullreportdata",
            name="excel_parts_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="fullreportdata",
            name="excel_parts_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
