# Generated by Django 5.1.3 on 2025-01-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0009_fullreportdata_excel_damage_lank_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partsname",
            name="工種",
            field=models.CharField(
                blank=True,
                choices=[
                    ("上部構造", "上部構造"),
                    ("下部構造", "下部構造"),
                    ("カルバート", "カルバート"),
                    ("支承部", "支承部"),
                    ("路上", "路上"),
                    ("排水施設", "排水施設"),
                    ("その他", "その他"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
