# Generated by Django 5.1.3 on 2025-03-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0010_partsname_工種"),
    ]

    operations = [
        migrations.AddField(
            model_name="bridgepicture",
            name="picture_count",
            field=models.TextField(blank=True, null=True),
        ),
    ]
